# hostname (and path) to the root eg. https://appernetic.github.io/
baseurl = "https://brainicorn.github.io/"

# Remark if you want to disable multilingual support.
#DefaultContentLanguage = "en"

# If you want all of the languages to be put below their respective language code,
# enable DefaultContentLanguageInSubdir = true. Without enabling it english content
# will be in the root and other languages in their respective subfolder such as /sv/.
# See [Languages] settings at the end of this file.

# Use this languageCode if it's not a multilingual site and also remove all language blocks and menus in the language sections to disable multilingual support.
# language blocks.
# Language
#languageCode = "en"

# SES friendly url:s
canonifyurls = true

# Frontmatter format
# "yaml", "toml", "json"
metaDataFormat = "toml"

# Theme to use (located in /themes/THEMENAME/)
theme = "hugo-bootstrap-premium"
# Pagination
paginate = 10
paginatePath = "page"

# Enable Disqus integration
disqusShortname = "brainicorn"

title = "Brainicorn"


[permalinks]
post = "/:year/:month/:day/:slug/"
code = "/:slug/"

[taxonomies]
tag = "tags"
topic = "topics"

[author]
name = "Brainicorn"
email = "dev@brainicorn.com"

#
# All parameters below here are optional and can be mixed and matched.
#
[params]
bootswatchtheme = "flatly"

# menu for changing language. This changes languages with js and stores the choice with the help of JavaScript in a Cookie. Then the path is rewritten with pathnamereplace.js. The name of the md files needs to have the same name for each language abbreviation to work correctly. Example: showcase.en.md and showcase.sv.md. It only works if DefaultContentLanguageInSubdir = true
switchlang = false
# You can use markdown here.
BrandImage = "/images/brainicorn-logo-oneline-wht-60h.png" #top header brand image.
brand = "Brainicorn" # brand image alt text.
topline = ""
footline = "Mythical Ideas."

customJS = []
customCSS = ["/brainicorn-custom.css"]

# Text for the top menu link, which goes to the root URL for the site.
# Default (if omitted) is "Home".
home = "home"

mailmunchid = "" # Mailmunch site id
sumomeid = "" # Sumome id
mathjax = "" # cdnjs hosted version; empty string to disable mathjax

# Show a sidebar menu
showRightSidebar = false

# Select a syntax highlight.
# Check the static/css/highlight directory for options.
highlight = "github"

# Google Analytics.
googleAnalytics = ""

# Sidebar social links.
github = "brainicorn" # Your Github profile ID
bitbucket = "" # Your Bitbucket profile ID
linkedin = "" # Your LinkedIn profile ID (from public URL)
googleplus = "" # Your Google+ profile ID
facebook = "" # Your Facebook profile ID
twitter = "brainicorndev" # Your Twitter profile ID
youtube = ""  # Your Youtube channel ID
flattr = ""  # populate with your flattr uid

[blackfriday]
angledQuotes = true
fractions = false
hrefTargetBlank = false
latexDashes = true
plainIdAnchors = true
extensions = []
extensionmask = []

[[menu.main]]
name = "Home"
weight = 1
identifier = "home"
url = "/"

# [[menu.main]]
# name = "Projects"
# weight = 2
# identifier = "projects"
# url = "/project/"
# [[menu.main]]
# name = "Blog2"
# weight = 2
# identifier = "post2"
# url = "/post/"
# [[menu.main]]
# name = "Projects"
# weight = 3
# identifier = "project"
# url = "/project/"
# Menus
# If you want active menu items highlighted for internal pages don't add them here, they need to be added in each files front matter.
# like this:
#[menu]
#     [menu.main]
#        name = "Showcase"
#        weight = 3
#        identifier = "showcase"
# i18n menus. A menu will be added for each language to the right in the top menu. This menu will switch to the selected language. Remember to add the corresponding language in pathnamereplace.js.
#[[Languages.sv.menu.switchlang]]
#  name = "English"
#  identifier = ""
#  weight = 4
#  url = "en"


# [Languages]
# [Languages.en]
# languageCode = "en"
# weight = 1
# copyright = "(c) 2016 Copyright my blog"
# title = "My blog" # Site title
#
# [[Languages.en.menu.main]]
# name = "Blog"
# pre = ""
# weight = 2
# identifier = "post"
# url = "/post/"
#
# [[Languages.en.menu.main]]
# name = "About"
# weight = 1
# identifier = ""
# url = "https://appernetic.io/app/#/about"
#
# [[Languages.en.menu.main]]
# name = "Dashboard"
# identifier = ""
# weight = 3
# url = "https://appernetic.io/app/"
#
# [[Languages.en.menu.footer]] # add  links to the bottom right corner.
# name = "Disclaimer"
# pre = "<i>&middot;</i>"
# identifier = "disclaimer"
# weight = 1
# url = "/disclaimer/"
#
# [[Languages.en.menu.footer]]
# name = "Terms"
# identifier = "terms"
# weight = 2
# url = "/terms/"

# [Languages.sv]
# languageCode = "sv"
# weight = 2
# title = "Min blog" # Site title
# copyright = "(c) 2016 Alla rättigheter"
#
# [[Languages.sv.menu.main]]
# name = "Bloggen"
# pre = ""
# weight = 2
# identifier = "post"
# url = "/sv/post/"
#
# [[Languages.sv.menu.footer]] # add  links to the bottom right corner.
# name = "Ansvarsfriskrivning"
# pre = "<i>&middot;</i>"
# identifier = "friskrivning"
# weight = 1
# url = "/sv/friskrivning/"
#
# [[Languages.sv.menu.footer]]
# name = "Vilkor"
# identifier = "vilkor"
# weight = 2
# url = "/sv/vilkor/"
#
# [Languages.sv.taxonomies]
# tag = "Taggar"
# topic = "Ämne"
